version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news-aggregator-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: news-aggregator-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: news_aggregator
      MYSQL_ROOT_PASSWORD: Webnyxa@2020
      # MYSQL_USER: root
      MYSQL_PASSWORD: Webnyxa@2020
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: news-aggregator-redis
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: news-aggregator-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
